apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: httpd
    name: httpd
  spec:
    replicas: 1
    selector:
      app: httpd
      deploymentconfig: httpd
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.httpd.image.entrypoint: '["httpd-foreground"]'
        creationTimestamp: null
        labels:
          app: httpd
          deploymentconfig: httpd
      spec:
        containers:
        - image: quay.io/swinches/httpd:latest
          imagePullPolicy: IfNotPresent
          name: httpd
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /logs
            name: httpd-volume-1
        - image: quay.io/swinches/fluentd:latest
          imagePullPolicy: Always
          name: fluentd
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /logs
            name: httpd-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: httpd-volume-1
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: httpd
    name: httpd
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: httpd
      deploymentconfig: httpd
  status:
    loadBalancer: {}